# Generated by Django 6.0.1 on 2026-02-28 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='Unique browser/device identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lock attempt to prevent multiple devices'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='security_violations',
            field=models.JSONField(default=list, help_text='List of security violations'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='session_token',
            field=models.CharField(blank=True, help_text='Unique session identifier', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='tab_switch_count',
            field=models.IntegerField(default=0, help_text='Number of tab switches detected'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['device_fingerprint'], name='exam_attemp_device__be6643_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['session_token'], name='exam_attemp_session_e40084_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['is_locked'], name='exam_attemp_is_lock_c1fa3a_idx'),
        ),
    ]
