# Generated by Django 6.0.1 on 2026-02-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examattempt_device_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='away_from_keyboard_count',
            field=models.IntegerField(default=0, help_text='Number of AFK events'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='face_detection_count',
            field=models.IntegerField(default=0, help_text='Number of face detection events'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='keystroke_pattern',
            field=models.JSONField(default=dict, help_text='Keystroke timing analysis'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='mouse_movement_pattern',
            field=models.JSONField(default=dict, help_text='Mouse movement analysis data'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='proctoring_log',
            field=models.JSONField(default=list, help_text='Detailed proctoring events'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='suspicious_activity_score',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='AI-calculated suspiciousness score', max_digits=5),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='webcam_monitored',
            field=models.BooleanField(default=False, help_text='Webcam monitoring flag (simulated)'),
        ),
    ]
