# Generated by Django 6.0.1 on 2026-02-28 07:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examattempt_away_from_keyboard_count_and_more'),
        ('questions', '0002_studentanswer_feedback_studentanswer_graded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_questions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(480)])),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('passing_marks', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('randomize_questions', models.BooleanField(default=True)),
                ('randomize_options', models.BooleanField(default=True)),
                ('allow_reuse_in_same_exam', models.BooleanField(default=False, help_text='Allow same question multiple times in one exam')),
                ('prevent_recent_reuse', models.BooleanField(default=True, help_text='Prevent questions used recently by same student')),
                ('recent_reuse_days', models.IntegerField(default=7, help_text='Days to prevent recent reuse')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_templates', to='exams.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('easy_percentage', models.IntegerField(default=40, help_text='Target percentage of easy questions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('medium_percentage', models.IntegerField(default=40, help_text='Target percentage of medium questions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hard_percentage', models.IntegerField(default=20, help_text='Target percentage of hard questions', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='exams.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_override', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Override default difficulty for this bank', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, help_text='Selection weight (higher = more likely to be selected)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5.0)])),
                ('tags', models.JSONField(default=list, help_text='Tags for categorization and selection')),
                ('usage_count', models.IntegerField(default=0, help_text='Times this question has been used in generated exams')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_entries', to='questions.question')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_questions', to='questions.questionbank')),
            ],
            options={
                'db_table': 'bank_questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionUsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('question_number', models.IntegerField(help_text='Position of question in exam')),
                ('time_spent_seconds', models.IntegerField(blank=True, help_text='Time student spent on this question', null=True)),
                ('is_correct', models.BooleanField(blank=True, help_text='Whether student answered correctly', null=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_usage', to='exams.exam')),
                ('generated_from_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.examtemplate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_history', to='questions.question')),
                ('selected_from_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.questionbank')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_usage_history',
            },
        ),
        migrations.CreateModel(
            name='TemplateBankRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_from_bank', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('difficulty_distribution', models.JSONField(default=dict, help_text='Difficulty distribution for this bank: {easy: X, medium: Y, hard: Z}')),
                ('question_types', models.JSONField(default=list, help_text="Allowed question types: ['mcq', 'true_false', 'short_answer', 'essay']")),
                ('tags_required', models.JSONField(default=list, help_text='Required tags for questions from this bank')),
                ('tags_excluded', models.JSONField(default=list, help_text='Tags to exclude from this bank')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionbank')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.examtemplate')),
            ],
            options={
                'db_table': 'template_bank_rules',
            },
        ),
        migrations.AddField(
            model_name='examtemplate',
            name='question_banks',
            field=models.ManyToManyField(through='questions.TemplateBankRule', to='questions.questionbank'),
        ),
        migrations.CreateModel(
            name='GeneratedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_seed', models.CharField(help_text='Seed used for random generation', max_length=32)),
                ('questions_used', models.JSONField(help_text='List of question IDs and their sources')),
                ('generation_time', models.DateTimeField(auto_now_add=True)),
                ('difficulty_distribution', models.JSONField(help_text='Actual difficulty distribution achieved')),
                ('question_type_distribution', models.JSONField(help_text='Actual question type distribution')),
                ('bank_distribution', models.JSONField(help_text='Questions from each bank')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_info', to='exams.exam')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_exams', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_exams', to='questions.examtemplate')),
            ],
            options={
                'db_table': 'generated_exams',
                'indexes': [models.Index(fields=['template', 'generation_time'], name='generated_e_templat_493a0d_idx'), models.Index(fields=['generated_by'], name='generated_e_generat_d495d3_idx'), models.Index(fields=['generation_seed'], name='generated_e_generat_19656b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['course', 'is_active'], name='question_ba_course__d6eec7_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['created_by'], name='question_ba_created_24be15_idx'),
        ),
        migrations.AddIndex(
            model_name='bankquestion',
            index=models.Index(fields=['bank', 'difficulty_override'], name='bank_questi_bank_id_af135d_idx'),
        ),
        migrations.AddIndex(
            model_name='bankquestion',
            index=models.Index(fields=['bank', 'weight'], name='bank_questi_bank_id_1ef65c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankquestion',
            index=models.Index(fields=['last_used'], name='bank_questi_last_us_af25b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankquestion',
            unique_together={('question', 'bank')},
        ),
        migrations.AddIndex(
            model_name='questionusagehistory',
            index=models.Index(fields=['question', 'used_at'], name='question_us_questio_6b0320_idx'),
        ),
        migrations.AddIndex(
            model_name='questionusagehistory',
            index=models.Index(fields=['student', 'used_at'], name='question_us_student_51137a_idx'),
        ),
        migrations.AddIndex(
            model_name='questionusagehistory',
            index=models.Index(fields=['generated_from_template'], name='question_us_generat_708ed4_idx'),
        ),
        migrations.AddIndex(
            model_name='questionusagehistory',
            index=models.Index(fields=['selected_from_bank'], name='question_us_selecte_f82c73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questionusagehistory',
            unique_together={('question', 'exam', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='templatebankrule',
            unique_together={('template', 'bank')},
        ),
        migrations.AddIndex(
            model_name='examtemplate',
            index=models.Index(fields=['course', 'is_active'], name='exam_templa_course__ba2a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='examtemplate',
            index=models.Index(fields=['created_by'], name='exam_templa_created_594975_idx'),
        ),
    ]
