# Generated by Django 6.0.1 on 2026-04-15 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_options_question_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankquestion',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='bankquestion',
            name='bank_questi_bank_id_af135d_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankquestion',
            name='bank_questi_bank_id_1ef65c_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankquestion',
            name='bank_questi_last_us_af25b4_idx',
        ),
        migrations.AlterModelOptions(
            name='questionbank',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='questionbank',
            name='question_ba_course__d6eec7_idx',
        ),
        migrations.RemoveIndex(
            model_name='questionbank',
            name='question_ba_created_24be15_idx',
        ),
        migrations.AddField(
            model_name='question',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.questionbank'),
        ),
        migrations.AddField(
            model_name='question',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for categorization'),
        ),
        migrations.AddField(
            model_name='question',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Times this question has been used'),
        ),
        migrations.AlterModelTable(
            name='questionbank',
            table=None,
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='easy_percentage',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='hard_percentage',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='medium_percentage',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='BankQuestion',
        ),
    ]
